// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  combatantKey: __t.string().primaryKey().name("combatant_key"),
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  combatantId: __t.string().name("combatant_id"),
  side: __t.string(),
  slotIndex: __t.u32().name("slot_index"),
  label: __t.string(),
  subtitle: __t.option(__t.string()),
  portraitUrl: __t.option(__t.string()).name("portrait_url"),
  resolve: __t.f64(),
  maxResolve: __t.f64().name("max_resolve"),
  ap: __t.f64(),
  maxAp: __t.f64().name("max_ap"),
  block: __t.f64(),
  nextIntentCardId: __t.option(__t.string()).name("next_intent_card_id"),
  nextIntentLabel: __t.option(__t.string()).name("next_intent_label"),
  nextIntentSummary: __t.option(__t.string()).name("next_intent_summary"),
  initiative: __t.option(__t.f64()),
  statusesJson: __t.string().name("statuses_json"),
  targetRulesJson: __t.option(__t.string()).name("target_rules_json"),
  resourceExtrasJson: __t.option(__t.string()).name("resource_extras_json"),
  updatedAt: __t.timestamp().name("updated_at"),
});
