// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionKey: __t.string().primaryKey().name("session_key"),
  playerId: __t.identity().name("player_id"),
  scenarioId: __t.string().name("scenario_id"),
  sourceTab: __t.string().name("source_tab"),
  returnTab: __t.string().name("return_tab"),
  sourceContextId: __t.option(__t.string()).name("source_context_id"),
  sourceScenarioId: __t.option(__t.string()).name("source_scenario_id"),
  phase: __t.string(),
  status: __t.string(),
  turnCount: __t.u32().name("turn_count"),
  drawPerTurn: __t.u32().name("draw_per_turn"),
  enemyIntentCursor: __t.u32().name("enemy_intent_cursor"),
  title: __t.string(),
  briefing: __t.string(),
  resolveLabel: __t.string().name("resolve_label"),
  apLabel: __t.string().name("ap_label"),
  blockLabel: __t.string().name("block_label"),
  backgroundUrl: __t.option(__t.string()).name("background_url"),
  resultType: __t.option(__t.string()).name("result_type"),
  resultTitle: __t.option(__t.string()).name("result_title"),
  resultSummary: __t.option(__t.string()).name("result_summary"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  closedAt: __t.option(__t.timestamp()).name("closed_at"),
});
