// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memberKey: __t.string().primaryKey().name("member_key"),
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  actorId: __t.string().name("actor_id"),
  label: __t.string(),
  role: __t.string(),
  availability: __t.string(),
  trust: __t.f64(),
  notes: __t.option(__t.string()),
  sortOrder: __t.u32().name("sort_order"),
  updatedAt: __t.timestamp().name("updated_at"),
});
