// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  varId: __t.string().primaryKey().name("var_id"),
  playerId: __t.identity().name("player_id"),
  key: __t.string(),
  floatValue: __t.f64().name("float_value"),
  updatedAt: __t.timestamp().name("updated_at"),
});
