// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  playerId: __t.identity().name("player_id"),
  templateId: __t.string().name("template_id"),
  snapshotChecksum: __t.string().name("snapshot_checksum"),
  payloadJson: __t.string().name("payload_json"),
  sourceLocationId: __t.string().name("source_location_id"),
  status: __t.string(),
  spawnedAt: __t.timestamp().name("spawned_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
});
