// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  spiritStateKey: __t.string().primaryKey().name("spirit_state_key"),
  playerId: __t.identity().name("player_id"),
  spiritId: __t.string().name("spirit_id"),
  state: __t.string(),
  method: __t.option(__t.string()),
  imprisonmentItemId: __t.option(__t.string()).name("imprisonment_item_id"),
  capturedAt: __t.option(__t.timestamp()).name("captured_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
