// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  auditId: __t.u64().primaryKey().name("audit_id"),
  actorIdentity: __t.identity().name("actor_identity"),
  actorRole: __t.string().name("actor_role"),
  action: __t.string(),
  subjectType: __t.string().name("subject_type"),
  subjectId: __t.string().name("subject_id"),
  summary: __t.string(),
  detailsJson: __t.string().name("details_json"),
  createdAt: __t.timestamp().name("created_at"),
});
