// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  historyKey: __t.string().primaryKey().name("history_key"),
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  turnCount: __t.u32().name("turn_count"),
  entryType: __t.string().name("entry_type"),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
