// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  version: __t.string().primaryKey(),
  checksum: __t.string(),
  schemaVersion: __t.u32().name("schema_version"),
  publishedAt: __t.timestamp().name("published_at"),
  isActive: __t.bool().name("is_active"),
});
