// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sourceId: __t.u64().name("source_id"),
  reportId: __t.u64().name("report_id"),
  evidenceId: __t.string().name("evidence_id"),
  kind: __t.string(),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  scenarioId: __t.option(__t.string()).name("scenario_id"),
  nodeId: __t.option(__t.string()).name("node_id"),
  contentVersion: __t.option(__t.string()).name("content_version"),
  raterHash: __t.string().name("rater_hash"),
  scoresJson: __t.string().name("scores_json"),
  comment: __t.option(__t.string()),
  ratedAt: __t.timestamp().name("rated_at"),
});
