// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  reportId: __t.u64().name("report_id"),
  reportKey: __t.string().name("report_key"),
  version: __t.u32(),
  requestedBy: __t.identity().name("requested_by"),
  filtersJson: __t.string().name("filters_json"),
  outputLanguage: __t.string().name("output_language"),
  status: __t.string(),
  reviewState: __t.string().name("review_state"),
  snapshotHash: __t.string().name("snapshot_hash"),
  sourceCount: __t.u32().name("source_count"),
  aiRequestId: __t.option(__t.u64()).name("ai_request_id"),
  resultJson: __t.option(__t.string()).name("result_json"),
  developerNote: __t.option(__t.string()).name("developer_note"),
  aiMetaJson: __t.option(__t.string()).name("ai_meta_json"),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
