// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdvanceQuestReducer from "./advance_quest_reducer";
import BeginFreiburgOriginReducer from "./begin_freiburg_origin_reducer";
import BuyItemReducer from "./buy_item_reducer";
import ChangeRelationshipReducer from "./change_relationship_reducer";
import CloseBattleModeReducer from "./close_battle_mode_reducer";
import CloseCommandModeReducer from "./close_command_mode_reducer";
import DeliverThoughtReducer from "./deliver_thought_reducer";
import DiscoverFactReducer from "./discover_fact_reducer";
import EndBattleTurnReducer from "./end_battle_turn_reducer";
import EnqueueAiRequestReducer from "./enqueue_ai_request_reducer";
import GrantEvidenceReducer from "./grant_evidence_reducer";
import GrantItemReducer from "./grant_item_reducer";
import GrantXpReducer from "./grant_xp_reducer";
import IssueCommandReducer from "./issue_command_reducer";
import MapInteractReducer from "./map_interact_reducer";
import OpenBattleModeReducer from "./open_battle_mode_reducer";
import OpenCommandModeReducer from "./open_command_mode_reducer";
import PerformSkillCheckReducer from "./perform_skill_check_reducer";
import PlayBattleCardReducer from "./play_battle_card_reducer";
import PublishContentReducer from "./publish_content_reducer";
import RecordChoiceReducer from "./record_choice_reducer";
import RedeemMapCodeReducer from "./redeem_map_code_reducer";
import RegisterWorkerIdentityReducer from "./register_worker_identity_reducer";
import ResolveCommandReducer from "./resolve_command_reducer";
import RollbackContentReducer from "./rollback_content_reducer";
import SetFlagReducer from "./set_flag_reducer";
import SetHypothesisFocusReducer from "./set_hypothesis_focus_reducer";
import SetNicknameReducer from "./set_nickname_reducer";
import SetQuestStageReducer from "./set_quest_stage_reducer";
import SetVarReducer from "./set_var_reducer";
import StartMindCaseReducer from "./start_mind_case_reducer";
import StartScenarioReducer from "./start_scenario_reducer";
import TrackEventReducer from "./track_event_reducer";
import TravelToReducer from "./travel_to_reducer";
import UnlockGroupReducer from "./unlock_group_reducer";
import ValidateHypothesisReducer from "./validate_hypothesis_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AiRequestRow from "./ai_request_table";
import BattleCardInstanceRow from "./battle_card_instance_table";
import BattleCombatantRow from "./battle_combatant_table";
import BattleHistoryRow from "./battle_history_table";
import BattleSessionRow from "./battle_session_table";
import CommandOrderHistoryRow from "./command_order_history_table";
import CommandPartyMemberRow from "./command_party_member_table";
import CommandSessionRow from "./command_session_table";
import ContentSnapshotRow from "./content_snapshot_table";
import ContentVersionRow from "./content_version_table";
import IdempotencyLogRow from "./idempotency_log_table";
import MindCaseRow from "./mind_case_table";
import MindFactRow from "./mind_fact_table";
import MindHypothesisRow from "./mind_hypothesis_table";
import PlayerEvidenceRow from "./player_evidence_table";
import PlayerFlagRow from "./player_flag_table";
import PlayerInventoryRow from "./player_inventory_table";
import PlayerLocationRow from "./player_location_table";
import PlayerMapEventRow from "./player_map_event_table";
import PlayerMindCaseRow from "./player_mind_case_table";
import PlayerMindFactRow from "./player_mind_fact_table";
import PlayerMindHypothesisRow from "./player_mind_hypothesis_table";
import PlayerProfileRow from "./player_profile_table";
import PlayerQuestRow from "./player_quest_table";
import PlayerRedeemedCodeRow from "./player_redeemed_code_table";
import PlayerRelationshipRow from "./player_relationship_table";
import PlayerUnlockGroupRow from "./player_unlock_group_table";
import PlayerVarRow from "./player_var_table";
import TelemetryAggregateRow from "./telemetry_aggregate_table";
import TelemetryEventRow from "./telemetry_event_table";
import VnSessionRow from "./vn_session_table";
import VnSkillCheckResultRow from "./vn_skill_check_result_table";
import WorkerIdentityRow from "./worker_identity_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  aiRequest: __table({
    name: 'ai_request',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'ai_request_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'ai_request_request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
      { name: 'ai_request_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'ai_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiRequestRow),
  battleCardInstance: __table({
    name: 'battle_card_instance',
    indexes: [
      { name: 'cardInstanceKey', algorithm: 'btree', columns: [
        'cardInstanceKey',
      ] },
      { name: 'battle_card_instance_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'battle_card_instance_session_key', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
      { name: 'battle_card_instance_zone', algorithm: 'btree', columns: [
        'zone',
      ] },
    ],
    constraints: [
      { name: 'battle_card_instance_card_instance_key_key', constraint: 'unique', columns: ['cardInstanceKey'] },
    ],
  }, BattleCardInstanceRow),
  battleCombatant: __table({
    name: 'battle_combatant',
    indexes: [
      { name: 'combatantKey', algorithm: 'btree', columns: [
        'combatantKey',
      ] },
      { name: 'battle_combatant_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'battle_combatant_session_key', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
      { name: 'battle_combatant_side', algorithm: 'btree', columns: [
        'side',
      ] },
    ],
    constraints: [
      { name: 'battle_combatant_combatant_key_key', constraint: 'unique', columns: ['combatantKey'] },
    ],
  }, BattleCombatantRow),
  battleHistory: __table({
    name: 'battle_history',
    indexes: [
      { name: 'historyKey', algorithm: 'btree', columns: [
        'historyKey',
      ] },
      { name: 'battle_history_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'battle_history_session_key', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
      { name: 'battle_history_turn_count', algorithm: 'btree', columns: [
        'turnCount',
      ] },
    ],
    constraints: [
      { name: 'battle_history_history_key_key', constraint: 'unique', columns: ['historyKey'] },
    ],
  }, BattleHistoryRow),
  battleSession: __table({
    name: 'battle_session',
    indexes: [
      { name: 'battle_session_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'battle_session_scenario_id', algorithm: 'btree', columns: [
        'scenarioId',
      ] },
      { name: 'sessionKey', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
      { name: 'battle_session_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'battle_session_session_key_key', constraint: 'unique', columns: ['sessionKey'] },
    ],
  }, BattleSessionRow),
  commandOrderHistory: __table({
    name: 'command_order_history',
    indexes: [
      { name: 'historyKey', algorithm: 'btree', columns: [
        'historyKey',
      ] },
      { name: 'command_order_history_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'command_order_history_scenario_id', algorithm: 'btree', columns: [
        'scenarioId',
      ] },
      { name: 'command_order_history_session_key', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
    ],
    constraints: [
      { name: 'command_order_history_history_key_key', constraint: 'unique', columns: ['historyKey'] },
    ],
  }, CommandOrderHistoryRow),
  commandPartyMember: __table({
    name: 'command_party_member',
    indexes: [
      { name: 'command_party_member_actor_id', algorithm: 'btree', columns: [
        'actorId',
      ] },
      { name: 'memberKey', algorithm: 'btree', columns: [
        'memberKey',
      ] },
      { name: 'command_party_member_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'command_party_member_session_key', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
    ],
    constraints: [
      { name: 'command_party_member_member_key_key', constraint: 'unique', columns: ['memberKey'] },
    ],
  }, CommandPartyMemberRow),
  commandSession: __table({
    name: 'command_session',
    indexes: [
      { name: 'command_session_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'command_session_scenario_id', algorithm: 'btree', columns: [
        'scenarioId',
      ] },
      { name: 'sessionKey', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
      { name: 'command_session_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'command_session_session_key_key', constraint: 'unique', columns: ['sessionKey'] },
    ],
  }, CommandSessionRow),
  contentSnapshot: __table({
    name: 'content_snapshot',
    indexes: [
      { name: 'checksum', algorithm: 'btree', columns: [
        'checksum',
      ] },
    ],
    constraints: [
      { name: 'content_snapshot_checksum_key', constraint: 'unique', columns: ['checksum'] },
    ],
  }, ContentSnapshotRow),
  contentVersion: __table({
    name: 'content_version',
    indexes: [
      { name: 'content_version_checksum', algorithm: 'btree', columns: [
        'checksum',
      ] },
      { name: 'content_version_is_active', algorithm: 'btree', columns: [
        'isActive',
      ] },
      { name: 'version', algorithm: 'btree', columns: [
        'version',
      ] },
    ],
    constraints: [
      { name: 'content_version_version_key', constraint: 'unique', columns: ['version'] },
    ],
  }, ContentVersionRow),
  idempotencyLog: __table({
    name: 'idempotency_log',
    indexes: [
      { name: 'idempotency_log_expires_at', algorithm: 'btree', columns: [
        'expiresAt',
      ] },
      { name: 'idempotencyKey', algorithm: 'btree', columns: [
        'idempotencyKey',
      ] },
      { name: 'idempotency_log_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'idempotency_log_idempotency_key_key', constraint: 'unique', columns: ['idempotencyKey'] },
    ],
  }, IdempotencyLogRow),
  mindCase: __table({
    name: 'mind_case',
    indexes: [
      { name: 'caseId', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'mind_case_is_active', algorithm: 'btree', columns: [
        'isActive',
      ] },
      { name: 'mind_case_schema_version', algorithm: 'btree', columns: [
        'schemaVersion',
      ] },
    ],
    constraints: [
      { name: 'mind_case_case_id_key', constraint: 'unique', columns: ['caseId'] },
    ],
  }, MindCaseRow),
  mindFact: __table({
    name: 'mind_fact',
    indexes: [
      { name: 'mind_fact_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'factId', algorithm: 'btree', columns: [
        'factId',
      ] },
      { name: 'mind_fact_source_id', algorithm: 'btree', columns: [
        'sourceId',
      ] },
      { name: 'mind_fact_source_type', algorithm: 'btree', columns: [
        'sourceType',
      ] },
    ],
    constraints: [
      { name: 'mind_fact_fact_id_key', constraint: 'unique', columns: ['factId'] },
    ],
  }, MindFactRow),
  mindHypothesis: __table({
    name: 'mind_hypothesis',
    indexes: [
      { name: 'mind_hypothesis_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'hypothesisId', algorithm: 'btree', columns: [
        'hypothesisId',
      ] },
      { name: 'mind_hypothesis_key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'mind_hypothesis_hypothesis_id_key', constraint: 'unique', columns: ['hypothesisId'] },
    ],
  }, MindHypothesisRow),
  playerEvidence: __table({
    name: 'player_evidence',
    indexes: [
      { name: 'player_evidence_evidence_id', algorithm: 'btree', columns: [
        'evidenceId',
      ] },
      { name: 'evidenceKey', algorithm: 'btree', columns: [
        'evidenceKey',
      ] },
      { name: 'player_evidence_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_evidence_evidence_key_key', constraint: 'unique', columns: ['evidenceKey'] },
    ],
  }, PlayerEvidenceRow),
  playerFlag: __table({
    name: 'player_flag',
    indexes: [
      { name: 'flagId', algorithm: 'btree', columns: [
        'flagId',
      ] },
      { name: 'player_flag_key', algorithm: 'btree', columns: [
        'key',
      ] },
      { name: 'player_flag_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_flag_flag_id_key', constraint: 'unique', columns: ['flagId'] },
    ],
  }, PlayerFlagRow),
  playerInventory: __table({
    name: 'player_inventory',
    indexes: [
      { name: 'inventoryKey', algorithm: 'btree', columns: [
        'inventoryKey',
      ] },
      { name: 'player_inventory_item_id', algorithm: 'btree', columns: [
        'itemId',
      ] },
      { name: 'player_inventory_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_inventory_inventory_key_key', constraint: 'unique', columns: ['inventoryKey'] },
    ],
  }, PlayerInventoryRow),
  playerLocation: __table({
    name: 'player_location',
    indexes: [
      { name: 'playerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_location_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, PlayerLocationRow),
  playerMapEvent: __table({
    name: 'player_map_event',
    indexes: [
      { name: 'eventId', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'player_map_event_expires_at', algorithm: 'btree', columns: [
        'expiresAt',
      ] },
      { name: 'player_map_event_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'player_map_event_status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'player_map_event_template_id', algorithm: 'btree', columns: [
        'templateId',
      ] },
    ],
    constraints: [
      { name: 'player_map_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, PlayerMapEventRow),
  playerMindCase: __table({
    name: 'player_mind_case',
    indexes: [
      { name: 'player_mind_case_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'playerCaseKey', algorithm: 'btree', columns: [
        'playerCaseKey',
      ] },
      { name: 'player_mind_case_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'player_mind_case_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'player_mind_case_player_case_key_key', constraint: 'unique', columns: ['playerCaseKey'] },
    ],
  }, PlayerMindCaseRow),
  playerMindFact: __table({
    name: 'player_mind_fact',
    indexes: [
      { name: 'player_mind_fact_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'player_mind_fact_fact_id', algorithm: 'btree', columns: [
        'factId',
      ] },
      { name: 'playerFactKey', algorithm: 'btree', columns: [
        'playerFactKey',
      ] },
      { name: 'player_mind_fact_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_mind_fact_player_fact_key_key', constraint: 'unique', columns: ['playerFactKey'] },
    ],
  }, PlayerMindFactRow),
  playerMindHypothesis: __table({
    name: 'player_mind_hypothesis',
    indexes: [
      { name: 'player_mind_hypothesis_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'player_mind_hypothesis_hypothesis_id', algorithm: 'btree', columns: [
        'hypothesisId',
      ] },
      { name: 'playerHypothesisKey', algorithm: 'btree', columns: [
        'playerHypothesisKey',
      ] },
      { name: 'player_mind_hypothesis_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'player_mind_hypothesis_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'player_mind_hypothesis_player_hypothesis_key_key', constraint: 'unique', columns: ['playerHypothesisKey'] },
    ],
  }, PlayerMindHypothesisRow),
  playerProfile: __table({
    name: 'player_profile',
    indexes: [
      { name: 'player_profile_nickname', algorithm: 'btree', columns: [
        'nickname',
      ] },
      { name: 'playerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_profile_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, PlayerProfileRow),
  playerQuest: __table({
    name: 'player_quest',
    indexes: [
      { name: 'player_quest_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'player_quest_quest_id', algorithm: 'btree', columns: [
        'questId',
      ] },
      { name: 'questKey', algorithm: 'btree', columns: [
        'questKey',
      ] },
    ],
    constraints: [
      { name: 'player_quest_quest_key_key', constraint: 'unique', columns: ['questKey'] },
    ],
  }, PlayerQuestRow),
  playerRedeemedCode: __table({
    name: 'player_redeemed_code',
    indexes: [
      { name: 'player_redeemed_code_code_id', algorithm: 'btree', columns: [
        'codeId',
      ] },
      { name: 'player_redeemed_code_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'redemptionId', algorithm: 'btree', columns: [
        'redemptionId',
      ] },
      { name: 'player_redeemed_code_request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
    ],
    constraints: [
      { name: 'player_redeemed_code_redemption_id_key', constraint: 'unique', columns: ['redemptionId'] },
    ],
  }, PlayerRedeemedCodeRow),
  playerRelationship: __table({
    name: 'player_relationship',
    indexes: [
      { name: 'player_relationship_character_id', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'player_relationship_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'relationshipKey', algorithm: 'btree', columns: [
        'relationshipKey',
      ] },
    ],
    constraints: [
      { name: 'player_relationship_relationship_key_key', constraint: 'unique', columns: ['relationshipKey'] },
    ],
  }, PlayerRelationshipRow),
  playerUnlockGroup: __table({
    name: 'player_unlock_group',
    indexes: [
      { name: 'player_unlock_group_group_id', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'player_unlock_group_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'unlockKey', algorithm: 'btree', columns: [
        'unlockKey',
      ] },
    ],
    constraints: [
      { name: 'player_unlock_group_unlock_key_key', constraint: 'unique', columns: ['unlockKey'] },
    ],
  }, PlayerUnlockGroupRow),
  playerVar: __table({
    name: 'player_var',
    indexes: [
      { name: 'player_var_key', algorithm: 'btree', columns: [
        'key',
      ] },
      { name: 'player_var_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'varId', algorithm: 'btree', columns: [
        'varId',
      ] },
    ],
    constraints: [
      { name: 'player_var_var_id_key', constraint: 'unique', columns: ['varId'] },
    ],
  }, PlayerVarRow),
  telemetryAggregate: __table({
    name: 'telemetry_aggregate',
    indexes: [
      { name: 'aggregateKey', algorithm: 'btree', columns: [
        'aggregateKey',
      ] },
      { name: 'telemetry_aggregate_bucket_start', algorithm: 'btree', columns: [
        'bucketStart',
      ] },
      { name: 'telemetry_aggregate_event_name', algorithm: 'btree', columns: [
        'eventName',
      ] },
    ],
    constraints: [
      { name: 'telemetry_aggregate_aggregate_key_key', constraint: 'unique', columns: ['aggregateKey'] },
    ],
  }, TelemetryAggregateRow),
  telemetryEvent: __table({
    name: 'telemetry_event',
    indexes: [
      { name: 'telemetry_event_created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'eventId', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'telemetry_event_event_name', algorithm: 'btree', columns: [
        'eventName',
      ] },
    ],
    constraints: [
      { name: 'telemetry_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, TelemetryEventRow),
  vnSession: __table({
    name: 'vn_session',
    indexes: [
      { name: 'vn_session_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'vn_session_scenario_id', algorithm: 'btree', columns: [
        'scenarioId',
      ] },
      { name: 'sessionKey', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
    ],
    constraints: [
      { name: 'vn_session_session_key_key', constraint: 'unique', columns: ['sessionKey'] },
    ],
  }, VnSessionRow),
  vnSkillCheckResult: __table({
    name: 'vn_skill_check_result',
    indexes: [
      { name: 'vn_skill_check_result_check_id', algorithm: 'btree', columns: [
        'checkId',
      ] },
      { name: 'vn_skill_check_result_player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'resultKey', algorithm: 'btree', columns: [
        'resultKey',
      ] },
      { name: 'vn_skill_check_result_scenario_id', algorithm: 'btree', columns: [
        'scenarioId',
      ] },
    ],
    constraints: [
      { name: 'vn_skill_check_result_result_key_key', constraint: 'unique', columns: ['resultKey'] },
    ],
  }, VnSkillCheckResultRow),
  workerIdentity: __table({
    name: 'worker_identity',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'worker_identity_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, WorkerIdentityRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("advance_quest", AdvanceQuestReducer),
  __reducerSchema("begin_freiburg_origin", BeginFreiburgOriginReducer),
  __reducerSchema("buy_item", BuyItemReducer),
  __reducerSchema("change_relationship", ChangeRelationshipReducer),
  __reducerSchema("close_battle_mode", CloseBattleModeReducer),
  __reducerSchema("close_command_mode", CloseCommandModeReducer),
  __reducerSchema("deliver_thought", DeliverThoughtReducer),
  __reducerSchema("discover_fact", DiscoverFactReducer),
  __reducerSchema("end_battle_turn", EndBattleTurnReducer),
  __reducerSchema("enqueue_ai_request", EnqueueAiRequestReducer),
  __reducerSchema("grant_evidence", GrantEvidenceReducer),
  __reducerSchema("grant_item", GrantItemReducer),
  __reducerSchema("grant_xp", GrantXpReducer),
  __reducerSchema("issue_command", IssueCommandReducer),
  __reducerSchema("map_interact", MapInteractReducer),
  __reducerSchema("open_battle_mode", OpenBattleModeReducer),
  __reducerSchema("open_command_mode", OpenCommandModeReducer),
  __reducerSchema("perform_skill_check", PerformSkillCheckReducer),
  __reducerSchema("play_battle_card", PlayBattleCardReducer),
  __reducerSchema("publish_content", PublishContentReducer),
  __reducerSchema("record_choice", RecordChoiceReducer),
  __reducerSchema("redeem_map_code", RedeemMapCodeReducer),
  __reducerSchema("register_worker_identity", RegisterWorkerIdentityReducer),
  __reducerSchema("resolve_command", ResolveCommandReducer),
  __reducerSchema("rollback_content", RollbackContentReducer),
  __reducerSchema("set_flag", SetFlagReducer),
  __reducerSchema("set_hypothesis_focus", SetHypothesisFocusReducer),
  __reducerSchema("set_nickname", SetNicknameReducer),
  __reducerSchema("set_quest_stage", SetQuestStageReducer),
  __reducerSchema("set_var", SetVarReducer),
  __reducerSchema("start_mind_case", StartMindCaseReducer),
  __reducerSchema("start_scenario", StartScenarioReducer),
  __reducerSchema("track_event", TrackEventReducer),
  __reducerSchema("travel_to", TravelToReducer),
  __reducerSchema("unlock_group", UnlockGroupReducer),
  __reducerSchema("validate_hypothesis", ValidateHypothesisReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
export const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}


// --- AUTOMATICALLY APPENDED BY POSTGENERATE.TS ---
const toSnakeCase = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toLowerCase();

for (const [key, table] of Object.entries(REMOTE_MODULE.tables)) {
    (table as any).sourceName = toSnakeCase(key);
}
// -------------------------------------------------
