// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdvanceQuestReducer from "./advance_quest_reducer";
import AllowWorkerIdentityReducer from "./allow_worker_identity_reducer";
import BeginFreiburgOriginReducer from "./begin_freiburg_origin_reducer";
import BeginKarlsruheEventEntryReducer from "./begin_karlsruhe_event_entry_reducer";
import BootstrapAdminIdentityReducer from "./bootstrap_admin_identity_reducer";
import BuyItemReducer from "./buy_item_reducer";
import ChangeAgencyStandingReducer from "./change_agency_standing_reducer";
import ChangeFactionSignalReducer from "./change_faction_signal_reducer";
import ChangeFavorBalanceReducer from "./change_favor_balance_reducer";
import ChangeRelationshipReducer from "./change_relationship_reducer";
import ClaimNextAiRequestReducer from "./claim_next_ai_request_reducer";
import CloseBattleModeReducer from "./close_battle_mode_reducer";
import CloseCommandModeReducer from "./close_command_mode_reducer";
import CompleteAiRequestReducer from "./complete_ai_request_reducer";
import DiscoverFactReducer from "./discover_fact_reducer";
import EndBattleTurnReducer from "./end_battle_turn_reducer";
import EnqueueAiRequestReducer from "./enqueue_ai_request_reducer";
import EnqueueProvidenceDialogueReducer from "./enqueue_providence_dialogue_reducer";
import FailAiRequestReducer from "./fail_ai_request_reducer";
import GrantAdminIdentityReducer from "./grant_admin_identity_reducer";
import GrantEvidenceReducer from "./grant_evidence_reducer";
import GrantItemReducer from "./grant_item_reducer";
import GrantXpReducer from "./grant_xp_reducer";
import IssueCommandReducer from "./issue_command_reducer";
import MapInteractReducer from "./map_interact_reducer";
import OpenBattleModeReducer from "./open_battle_mode_reducer";
import OpenCommandModeReducer from "./open_command_mode_reducer";
import PerformSkillCheckReducer from "./perform_skill_check_reducer";
import PlayBattleCardReducer from "./play_battle_card_reducer";
import PublishContentReducer from "./publish_content_reducer";
import RecordChoiceReducer from "./record_choice_reducer";
import RecordServiceCriterionReducer from "./record_service_criterion_reducer";
import RedeemMapCodeReducer from "./redeem_map_code_reducer";
import RegisterRumorReducer from "./register_rumor_reducer";
import RegisterWorkerIdentityReducer from "./register_worker_identity_reducer";
import RenewAiRequestLeaseReducer from "./renew_ai_request_lease_reducer";
import RequeueAiRequestReducer from "./requeue_ai_request_reducer";
import ResolveCommandReducer from "./resolve_command_reducer";
import RollbackContentReducer from "./rollback_content_reducer";
import SetFlagReducer from "./set_flag_reducer";
import SetHypothesisFocusReducer from "./set_hypothesis_focus_reducer";
import SetNicknameReducer from "./set_nickname_reducer";
import SetQuestStageReducer from "./set_quest_stage_reducer";
import SetVarReducer from "./set_var_reducer";
import StartMindCaseReducer from "./start_mind_case_reducer";
import StartScenarioReducer from "./start_scenario_reducer";
import TrackEventReducer from "./track_event_reducer";
import TravelToReducer from "./travel_to_reducer";
import UnlockGroupReducer from "./unlock_group_reducer";
import ValidateHypothesisReducer from "./validate_hypothesis_reducer";
import VerifyRumorReducer from "./verify_rumor_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ContentSnapshotRow from "./content_snapshot_table";
import ContentVersionRow from "./content_version_table";
import MindCaseRow from "./mind_case_table";
import MindFactRow from "./mind_fact_table";
import MindHypothesisRow from "./mind_hypothesis_table";
import MyAgencyCareerRow from "./my_agency_career_table";
import MyAiRequestsRow from "./my_ai_requests_table";
import MyBattleCardsRow from "./my_battle_cards_table";
import MyBattleCombatantsRow from "./my_battle_combatants_table";
import MyBattleHistoryRow from "./my_battle_history_table";
import MyBattleSessionsRow from "./my_battle_sessions_table";
import MyCommandHistoryRow from "./my_command_history_table";
import MyCommandPartyRow from "./my_command_party_table";
import MyCommandSessionsRow from "./my_command_sessions_table";
import MyEvidenceRow from "./my_evidence_table";
import MyFactionSignalsRow from "./my_faction_signals_table";
import MyMapEventsRow from "./my_map_events_table";
import MyMindCasesRow from "./my_mind_cases_table";
import MyMindFactsRow from "./my_mind_facts_table";
import MyMindHypothesesRow from "./my_mind_hypotheses_table";
import MyNpcFavorsRow from "./my_npc_favors_table";
import MyNpcStateRow from "./my_npc_state_table";
import MyPlayerFlagsRow from "./my_player_flags_table";
import MyPlayerInventoryRow from "./my_player_inventory_table";
import MyPlayerLocationRow from "./my_player_location_table";
import MyPlayerProfileRow from "./my_player_profile_table";
import MyPlayerVarsRow from "./my_player_vars_table";
import MyQuestsRow from "./my_quests_table";
import MyRedeemedCodesRow from "./my_redeemed_codes_table";
import MyRelationshipsRow from "./my_relationships_table";
import MyRumorStateRow from "./my_rumor_state_table";
import MySpiritStateRow from "./my_spirit_state_table";
import MyUnlockGroupsRow from "./my_unlock_groups_table";
import MyVnSessionsRow from "./my_vn_sessions_table";
import MyVnSkillResultsRow from "./my_vn_skill_results_table";
import WorkerAiRequestsRow from "./worker_ai_requests_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  contentSnapshot: __table({
    name: 'content_snapshot',
    indexes: [
      { name: 'checksum', algorithm: 'btree', columns: [
        'checksum',
      ] },
    ],
    constraints: [
      { name: 'content_snapshot_checksum_key', constraint: 'unique', columns: ['checksum'] },
    ],
  }, ContentSnapshotRow),
  contentVersion: __table({
    name: 'content_version',
    indexes: [
      { name: 'content_version_checksum', algorithm: 'btree', columns: [
        'checksum',
      ] },
      { name: 'content_version_is_active', algorithm: 'btree', columns: [
        'isActive',
      ] },
      { name: 'version', algorithm: 'btree', columns: [
        'version',
      ] },
    ],
    constraints: [
      { name: 'content_version_version_key', constraint: 'unique', columns: ['version'] },
    ],
  }, ContentVersionRow),
  mindCase: __table({
    name: 'mind_case',
    indexes: [
      { name: 'caseId', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'mind_case_is_active', algorithm: 'btree', columns: [
        'isActive',
      ] },
      { name: 'mind_case_schema_version', algorithm: 'btree', columns: [
        'schemaVersion',
      ] },
    ],
    constraints: [
      { name: 'mind_case_case_id_key', constraint: 'unique', columns: ['caseId'] },
    ],
  }, MindCaseRow),
  mindFact: __table({
    name: 'mind_fact',
    indexes: [
      { name: 'mind_fact_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'factId', algorithm: 'btree', columns: [
        'factId',
      ] },
      { name: 'mind_fact_source_id', algorithm: 'btree', columns: [
        'sourceId',
      ] },
      { name: 'mind_fact_source_type', algorithm: 'btree', columns: [
        'sourceType',
      ] },
    ],
    constraints: [
      { name: 'mind_fact_fact_id_key', constraint: 'unique', columns: ['factId'] },
    ],
  }, MindFactRow),
  mindHypothesis: __table({
    name: 'mind_hypothesis',
    indexes: [
      { name: 'mind_hypothesis_case_id', algorithm: 'btree', columns: [
        'caseId',
      ] },
      { name: 'hypothesisId', algorithm: 'btree', columns: [
        'hypothesisId',
      ] },
      { name: 'mind_hypothesis_key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'mind_hypothesis_hypothesis_id_key', constraint: 'unique', columns: ['hypothesisId'] },
    ],
  }, MindHypothesisRow),
  my_agency_career: __table({
    name: 'my_agency_career',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAgencyCareerRow),
  my_ai_requests: __table({
    name: 'my_ai_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAiRequestsRow),
  my_battle_cards: __table({
    name: 'my_battle_cards',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBattleCardsRow),
  my_battle_combatants: __table({
    name: 'my_battle_combatants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBattleCombatantsRow),
  my_battle_history: __table({
    name: 'my_battle_history',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBattleHistoryRow),
  my_battle_sessions: __table({
    name: 'my_battle_sessions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBattleSessionsRow),
  my_command_history: __table({
    name: 'my_command_history',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCommandHistoryRow),
  my_command_party: __table({
    name: 'my_command_party',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCommandPartyRow),
  my_command_sessions: __table({
    name: 'my_command_sessions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCommandSessionsRow),
  my_evidence: __table({
    name: 'my_evidence',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEvidenceRow),
  my_faction_signals: __table({
    name: 'my_faction_signals',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFactionSignalsRow),
  my_map_events: __table({
    name: 'my_map_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMapEventsRow),
  my_mind_cases: __table({
    name: 'my_mind_cases',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMindCasesRow),
  my_mind_facts: __table({
    name: 'my_mind_facts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMindFactsRow),
  my_mind_hypotheses: __table({
    name: 'my_mind_hypotheses',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMindHypothesesRow),
  my_npc_favors: __table({
    name: 'my_npc_favors',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNpcFavorsRow),
  my_npc_state: __table({
    name: 'my_npc_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNpcStateRow),
  my_player_flags: __table({
    name: 'my_player_flags',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerFlagsRow),
  my_player_inventory: __table({
    name: 'my_player_inventory',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerInventoryRow),
  my_player_location: __table({
    name: 'my_player_location',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerLocationRow),
  my_player_profile: __table({
    name: 'my_player_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerProfileRow),
  my_player_vars: __table({
    name: 'my_player_vars',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerVarsRow),
  my_quests: __table({
    name: 'my_quests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyQuestsRow),
  my_redeemed_codes: __table({
    name: 'my_redeemed_codes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRedeemedCodesRow),
  my_relationships: __table({
    name: 'my_relationships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRelationshipsRow),
  my_rumor_state: __table({
    name: 'my_rumor_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRumorStateRow),
  my_spirit_state: __table({
    name: 'my_spirit_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MySpiritStateRow),
  my_unlock_groups: __table({
    name: 'my_unlock_groups',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUnlockGroupsRow),
  my_vn_sessions: __table({
    name: 'my_vn_sessions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyVnSessionsRow),
  my_vn_skill_results: __table({
    name: 'my_vn_skill_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyVnSkillResultsRow),
  worker_ai_requests: __table({
    name: 'worker_ai_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerAiRequestsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("advance_quest", AdvanceQuestReducer),
  __reducerSchema("allow_worker_identity", AllowWorkerIdentityReducer),
  __reducerSchema("begin_freiburg_origin", BeginFreiburgOriginReducer),
  __reducerSchema("begin_karlsruhe_event_entry", BeginKarlsruheEventEntryReducer),
  __reducerSchema("bootstrap_admin_identity", BootstrapAdminIdentityReducer),
  __reducerSchema("buy_item", BuyItemReducer),
  __reducerSchema("change_agency_standing", ChangeAgencyStandingReducer),
  __reducerSchema("change_faction_signal", ChangeFactionSignalReducer),
  __reducerSchema("change_favor_balance", ChangeFavorBalanceReducer),
  __reducerSchema("change_relationship", ChangeRelationshipReducer),
  __reducerSchema("claim_next_ai_request", ClaimNextAiRequestReducer),
  __reducerSchema("close_battle_mode", CloseBattleModeReducer),
  __reducerSchema("close_command_mode", CloseCommandModeReducer),
  __reducerSchema("complete_ai_request", CompleteAiRequestReducer),
  __reducerSchema("discover_fact", DiscoverFactReducer),
  __reducerSchema("end_battle_turn", EndBattleTurnReducer),
  __reducerSchema("enqueue_ai_request", EnqueueAiRequestReducer),
  __reducerSchema("enqueue_providence_dialogue", EnqueueProvidenceDialogueReducer),
  __reducerSchema("fail_ai_request", FailAiRequestReducer),
  __reducerSchema("grant_admin_identity", GrantAdminIdentityReducer),
  __reducerSchema("grant_evidence", GrantEvidenceReducer),
  __reducerSchema("grant_item", GrantItemReducer),
  __reducerSchema("grant_xp", GrantXpReducer),
  __reducerSchema("issue_command", IssueCommandReducer),
  __reducerSchema("map_interact", MapInteractReducer),
  __reducerSchema("open_battle_mode", OpenBattleModeReducer),
  __reducerSchema("open_command_mode", OpenCommandModeReducer),
  __reducerSchema("perform_skill_check", PerformSkillCheckReducer),
  __reducerSchema("play_battle_card", PlayBattleCardReducer),
  __reducerSchema("publish_content", PublishContentReducer),
  __reducerSchema("record_choice", RecordChoiceReducer),
  __reducerSchema("record_service_criterion", RecordServiceCriterionReducer),
  __reducerSchema("redeem_map_code", RedeemMapCodeReducer),
  __reducerSchema("register_rumor", RegisterRumorReducer),
  __reducerSchema("register_worker_identity", RegisterWorkerIdentityReducer),
  __reducerSchema("renew_ai_request_lease", RenewAiRequestLeaseReducer),
  __reducerSchema("requeue_ai_request", RequeueAiRequestReducer),
  __reducerSchema("resolve_command", ResolveCommandReducer),
  __reducerSchema("rollback_content", RollbackContentReducer),
  __reducerSchema("set_flag", SetFlagReducer),
  __reducerSchema("set_hypothesis_focus", SetHypothesisFocusReducer),
  __reducerSchema("set_nickname", SetNicknameReducer),
  __reducerSchema("set_quest_stage", SetQuestStageReducer),
  __reducerSchema("set_var", SetVarReducer),
  __reducerSchema("start_mind_case", StartMindCaseReducer),
  __reducerSchema("start_scenario", StartScenarioReducer),
  __reducerSchema("track_event", TrackEventReducer),
  __reducerSchema("travel_to", TravelToReducer),
  __reducerSchema("unlock_group", UnlockGroupReducer),
  __reducerSchema("validate_hypothesis", ValidateHypothesisReducer),
  __reducerSchema("verify_rumor", VerifyRumorReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
export const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}


// --- AUTOMATICALLY APPENDED BY POSTGENERATE.TS ---
const toSnakeCase = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toLowerCase();

for (const [key, table] of Object.entries(REMOTE_MODULE.tables)) {
    (table as any).sourceName = toSnakeCase(key);
}
// -------------------------------------------------

export {
  __DbConnectionBuilder,
  __DbConnectionImpl,
  __SubscriptionBuilderImpl,
  __convertToAccessorMap,
  __makeQueryBuilder,
  __schema,
  __t,
  __table,
};
