// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  hypothesisId: __t.string().primaryKey().name("hypothesis_id"),
  caseId: __t.string().name("case_id"),
  key: __t.string(),
  text: __t.string(),
  requiredFactIdsJson: __t.string().name("required_fact_ids_json"),
  requiredVarsJson: __t.string().name("required_vars_json"),
  rewardEffectsJson: __t.string().name("reward_effects_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
