// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cardInstanceKey: __t.string().name("card_instance_key"),
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  instanceId: __t.string().name("instance_id"),
  ownerCombatantId: __t.string().name("owner_combatant_id"),
  cardId: __t.string().name("card_id"),
  label: __t.string(),
  description: __t.string(),
  effectPreview: __t.string().name("effect_preview"),
  artUrl: __t.option(__t.string()).name("art_url"),
  tagsJson: __t.option(__t.string()).name("tags_json"),
  costAp: __t.f64().name("cost_ap"),
  zone: __t.string(),
  zoneOrder: __t.u32().name("zone_order"),
  isPlayable: __t.bool().name("is_playable"),
  playableReason: __t.option(__t.string()).name("playable_reason"),
  targetRule: __t.option(__t.string()).name("target_rule"),
  updatedAt: __t.timestamp().name("updated_at"),
});
