// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ratingId: __t.string().name("rating_id"),
  raterId: __t.identity().name("rater_id"),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  scenarioId: __t.option(__t.string()).name("scenario_id"),
  contentVersion: __t.option(__t.string()).name("content_version"),
  visualScore: __t.option(__t.u32()).name("visual_score"),
  scenicScore: __t.option(__t.u32()).name("scenic_score"),
  textScore: __t.option(__t.u32()).name("text_score"),
  overallScore: __t.option(__t.u32()).name("overall_score"),
  comment: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
