// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  scenarioId: __t.string().name("scenario_id"),
  sourceTab: __t.string().name("source_tab"),
  returnTab: __t.string().name("return_tab"),
  phase: __t.string(),
  status: __t.string(),
  title: __t.string(),
  briefing: __t.string(),
  ordersJson: __t.string().name("orders_json"),
  selectedOrderId: __t.option(__t.string()).name("selected_order_id"),
  resultTitle: __t.option(__t.string()).name("result_title"),
  resultSummary: __t.option(__t.string()).name("result_summary"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  closedAt: __t.option(__t.timestamp()).name("closed_at"),
});
