// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  historyKey: __t.string().name("history_key"),
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  scenarioId: __t.string().name("scenario_id"),
  orderId: __t.string().name("order_id"),
  actorId: __t.string().name("actor_id"),
  title: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
