// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ratingId: __t.string().name("rating_id"),
  raterId: __t.identity().name("rater_id"),
  nodeId: __t.string().name("node_id"),
  scenarioId: __t.option(__t.string()).name("scenario_id"),
  lineKey: __t.string().name("line_key"),
  speaker: __t.string(),
  segmentIndex: __t.u32().name("segment_index"),
  textHash: __t.string().name("text_hash"),
  contentVersion: __t.option(__t.string()).name("content_version"),
  score: __t.u32(),
  comment: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
