// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ledgerEntryKey: __t.string().name("ledger_entry_key"),
  playerId: __t.identity().name("player_id"),
  favorId: __t.string().name("favor_id"),
  npcId: __t.string().name("npc_id"),
  favorType: __t.string().name("favor_type"),
  weight: __t.i32(),
  sourceCaseId: __t.option(__t.string()).name("source_case_id"),
  sourceRumorId: __t.option(__t.string()).name("source_rumor_id"),
  note: __t.option(__t.string()),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
