// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signalKey: __t.string().name("signal_key"),
  playerId: __t.identity().name("player_id"),
  factionId: __t.string().name("faction_id"),
  value: __t.f64(),
  trend: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
