// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerLinkKey: __t.string().name("player_link_key"),
  playerId: __t.identity().name("player_id"),
  caseId: __t.string().name("case_id"),
  factId: __t.string().name("fact_id"),
  hypothesisId: __t.string().name("hypothesis_id"),
  createdAt: __t.timestamp().name("created_at"),
});
