// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerHypothesisKey: __t.string().name("player_hypothesis_key"),
  playerId: __t.identity().name("player_id"),
  caseId: __t.string().name("case_id"),
  hypothesisId: __t.string().name("hypothesis_id"),
  status: __t.string(),
  validatedAt: __t.option(__t.timestamp()).name("validated_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
