// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  favorKey: __t.string().name("favor_key"),
  playerId: __t.identity().name("player_id"),
  npcId: __t.string().name("npc_id"),
  balance: __t.i32(),
  lastReason: __t.option(__t.string()).name("last_reason"),
  updatedAt: __t.timestamp().name("updated_at"),
});
