// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questInstanceKey: __t.string().name("quest_instance_key"),
  playerId: __t.identity().name("player_id"),
  instanceId: __t.string().name("instance_id"),
  kind: __t.string(),
  status: __t.string(),
  triggerRuleId: __t.string().name("trigger_rule_id"),
  archetypeId: __t.string().name("archetype_id"),
  archetypeVersion: __t.u32().name("archetype_version"),
  bundleChecksum: __t.string().name("bundle_checksum"),
  stateNamespace: __t.string().name("state_namespace"),
  stepsJson: __t.string().name("steps_json"),
  eligibilitySnapshotJson: __t.string().name("eligibility_snapshot_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
