// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  redemptionId: __t.string().name("redemption_id"),
  playerId: __t.identity().name("player_id"),
  codeId: __t.string().name("code_id"),
  requestId: __t.string().name("request_id"),
  redeemedAt: __t.timestamp().name("redeemed_at"),
  result: __t.string(),
  attemptedFromLat: __t.option(__t.f64()).name("attempted_from_lat"),
  attemptedFromLng: __t.option(__t.f64()).name("attempted_from_lng"),
});
