// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rumorStateKey: __t.string().name("rumor_state_key"),
  playerId: __t.identity().name("player_id"),
  rumorId: __t.string().name("rumor_id"),
  status: __t.string(),
  leadPointId: __t.option(__t.string()).name("lead_point_id"),
  sourceNpcId: __t.option(__t.string()).name("source_npc_id"),
  caseId: __t.string().name("case_id"),
  verificationKind: __t.option(__t.string()).name("verification_kind"),
  verifiedAt: __t.option(__t.timestamp()).name("verified_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  sourceType: __t.option(__t.string()).name("source_type"),
  factionKey: __t.option(__t.string()).name("faction_key"),
  subject: __t.option(__t.string()),
  locationHint: __t.option(__t.string()).name("location_hint"),
  credibility: __t.option(__t.f64()),
  heatRisk: __t.option(__t.f64()).name("heat_risk"),
  resolvedCaseId: __t.option(__t.string()).name("resolved_case_id"),
  discoveredAt: __t.option(__t.timestamp()).name("discovered_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
});
