// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionKey: __t.string().name("session_key"),
  playerId: __t.identity().name("player_id"),
  scenarioId: __t.string().name("scenario_id"),
  nodeId: __t.string().name("node_id"),
  updatedAt: __t.timestamp().name("updated_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
