// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  metricKey: __t.string().primaryKey().name("metric_key"),
  label: __t.string(),
  source: __t.string(),
  status: __t.string(),
  summary: __t.string(),
  value: __t.f64(),
  hasValue: __t.bool().name("has_value"),
  unit: __t.string(),
  linkUrl: __t.string().name("link_url"),
  observedAt: __t.timestamp().name("observed_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
