// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.identity().primaryKey().name("player_id"),
  currentTab: __t.string().name("current_tab"),
  appVersion: __t.string().name("app_version"),
  buildCommit: __t.string().name("build_commit"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
