// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.identity().primaryKey().name("player_id"),
  standingScore: __t.f64().name("standing_score"),
  standingTrend: __t.string().name("standing_trend"),
  rankId: __t.string().name("rank_id"),
  qualifyingCaseId: __t.option(__t.string()).name("qualifying_case_id"),
  rumorCriterionComplete: __t.bool().name("rumor_criterion_complete"),
  sourceCriterionComplete: __t.bool().name("source_criterion_complete"),
  cleanClosureCriterionComplete: __t.bool().name("clean_closure_criterion_complete"),
  updatedAt: __t.timestamp().name("updated_at"),
  promotedAt: __t.option(__t.timestamp()).name("promoted_at"),
});
