// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcStateKey: __t.string().primaryKey().name("npc_state_key"),
  playerId: __t.identity().name("player_id"),
  npcId: __t.string().name("npc_id"),
  trustScore: __t.f64().name("trust_score"),
  availabilityState: __t.string().name("availability_state"),
  lastMeaningfulContactAt: __t.option(__t.timestamp()).name("last_meaningful_contact_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
