// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  aggregateKey: __t.string().primaryKey().name("aggregate_key"),
  bucketStart: __t.timestamp().name("bucket_start"),
  eventName: __t.string().name("event_name"),
  tagsHash: __t.string().name("tags_hash"),
  count: __t.u64(),
  sumValue: __t.f64().name("sum_value"),
  updatedAt: __t.timestamp().name("updated_at"),
});
