// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  playerId: __t.option(__t.identity()).name("player_id"),
  eventName: __t.string().name("event_name"),
  tagsJson: __t.string().name("tags_json"),
  value: __t.option(__t.f64()),
  createdAt: __t.timestamp().name("created_at"),
});
