// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiRequest = __t.object("AiRequest", {
  id: __t.u64(),
  playerId: __t.identity(),
  requestId: __t.string(),
  kind: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  responseJson: __t.option(__t.string()),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AiRequest = __Infer<typeof AiRequest>;

export const BattleCardInstance = __t.object("BattleCardInstance", {
  cardInstanceKey: __t.string(),
  sessionKey: __t.string(),
  playerId: __t.identity(),
  instanceId: __t.string(),
  ownerCombatantId: __t.string(),
  cardId: __t.string(),
  label: __t.string(),
  description: __t.string(),
  effectPreview: __t.string(),
  artUrl: __t.option(__t.string()),
  tagsJson: __t.option(__t.string()),
  costAp: __t.f64(),
  zone: __t.string(),
  zoneOrder: __t.u32(),
  isPlayable: __t.bool(),
  playableReason: __t.option(__t.string()),
  targetRule: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type BattleCardInstance = __Infer<typeof BattleCardInstance>;

export const BattleCombatant = __t.object("BattleCombatant", {
  combatantKey: __t.string(),
  sessionKey: __t.string(),
  playerId: __t.identity(),
  combatantId: __t.string(),
  side: __t.string(),
  slotIndex: __t.u32(),
  label: __t.string(),
  subtitle: __t.option(__t.string()),
  portraitUrl: __t.option(__t.string()),
  resolve: __t.f64(),
  maxResolve: __t.f64(),
  ap: __t.f64(),
  maxAp: __t.f64(),
  block: __t.f64(),
  nextIntentCardId: __t.option(__t.string()),
  nextIntentLabel: __t.option(__t.string()),
  nextIntentSummary: __t.option(__t.string()),
  initiative: __t.option(__t.f64()),
  statusesJson: __t.string(),
  targetRulesJson: __t.option(__t.string()),
  resourceExtrasJson: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type BattleCombatant = __Infer<typeof BattleCombatant>;

export const BattleHistory = __t.object("BattleHistory", {
  historyKey: __t.string(),
  sessionKey: __t.string(),
  playerId: __t.identity(),
  turnCount: __t.u32(),
  entryType: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type BattleHistory = __Infer<typeof BattleHistory>;

export const BattleSession = __t.object("BattleSession", {
  sessionKey: __t.string(),
  playerId: __t.identity(),
  scenarioId: __t.string(),
  sourceTab: __t.string(),
  returnTab: __t.string(),
  sourceContextId: __t.option(__t.string()),
  sourceScenarioId: __t.option(__t.string()),
  phase: __t.string(),
  status: __t.string(),
  turnCount: __t.u32(),
  drawPerTurn: __t.u32(),
  enemyIntentCursor: __t.u32(),
  title: __t.string(),
  briefing: __t.string(),
  resolveLabel: __t.string(),
  apLabel: __t.string(),
  blockLabel: __t.string(),
  backgroundUrl: __t.option(__t.string()),
  resultType: __t.option(__t.string()),
  resultTitle: __t.option(__t.string()),
  resultSummary: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  closedAt: __t.option(__t.timestamp()),
});
export type BattleSession = __Infer<typeof BattleSession>;

export const CommandOrderHistory = __t.object("CommandOrderHistory", {
  historyKey: __t.string(),
  sessionKey: __t.string(),
  playerId: __t.identity(),
  scenarioId: __t.string(),
  orderId: __t.string(),
  actorId: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type CommandOrderHistory = __Infer<typeof CommandOrderHistory>;

export const CommandPartyMember = __t.object("CommandPartyMember", {
  memberKey: __t.string(),
  sessionKey: __t.string(),
  playerId: __t.identity(),
  actorId: __t.string(),
  label: __t.string(),
  role: __t.string(),
  availability: __t.string(),
  trust: __t.f64(),
  notes: __t.option(__t.string()),
  sortOrder: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type CommandPartyMember = __Infer<typeof CommandPartyMember>;

export const CommandSession = __t.object("CommandSession", {
  sessionKey: __t.string(),
  playerId: __t.identity(),
  scenarioId: __t.string(),
  sourceTab: __t.string(),
  returnTab: __t.string(),
  phase: __t.string(),
  status: __t.string(),
  title: __t.string(),
  briefing: __t.string(),
  ordersJson: __t.string(),
  selectedOrderId: __t.option(__t.string()),
  resultTitle: __t.option(__t.string()),
  resultSummary: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  closedAt: __t.option(__t.timestamp()),
});
export type CommandSession = __Infer<typeof CommandSession>;

export const ContentSnapshot = __t.object("ContentSnapshot", {
  checksum: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type ContentSnapshot = __Infer<typeof ContentSnapshot>;

export const ContentVersion = __t.object("ContentVersion", {
  version: __t.string(),
  checksum: __t.string(),
  schemaVersion: __t.u32(),
  publishedAt: __t.timestamp(),
  isActive: __t.bool(),
});
export type ContentVersion = __Infer<typeof ContentVersion>;

export const IdempotencyCleanupSchedule = __t.object("IdempotencyCleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type IdempotencyCleanupSchedule = __Infer<typeof IdempotencyCleanupSchedule>;

export const IdempotencyLog = __t.object("IdempotencyLog", {
  idempotencyKey: __t.string(),
  playerId: __t.identity(),
  requestId: __t.string(),
  operation: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type IdempotencyLog = __Infer<typeof IdempotencyLog>;

export const MindCase = __t.object("MindCase", {
  caseId: __t.string(),
  title: __t.string(),
  schemaVersion: __t.u32(),
  isActive: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MindCase = __Infer<typeof MindCase>;

export const MindFact = __t.object("MindFact", {
  factId: __t.string(),
  caseId: __t.string(),
  sourceType: __t.string(),
  sourceId: __t.string(),
  text: __t.string(),
  tagsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type MindFact = __Infer<typeof MindFact>;

export const MindHypothesis = __t.object("MindHypothesis", {
  hypothesisId: __t.string(),
  caseId: __t.string(),
  key: __t.string(),
  text: __t.string(),
  requiredFactIdsJson: __t.string(),
  requiredVarsJson: __t.string(),
  rewardEffectsJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MindHypothesis = __Infer<typeof MindHypothesis>;

export const PlayerAgencyCareer = __t.object("PlayerAgencyCareer", {
  playerId: __t.identity(),
  standingScore: __t.f64(),
  standingTrend: __t.string(),
  rankId: __t.string(),
  qualifyingCaseId: __t.option(__t.string()),
  rumorCriterionComplete: __t.bool(),
  sourceCriterionComplete: __t.bool(),
  cleanClosureCriterionComplete: __t.bool(),
  updatedAt: __t.timestamp(),
  promotedAt: __t.option(__t.timestamp()),
});
export type PlayerAgencyCareer = __Infer<typeof PlayerAgencyCareer>;

export const PlayerEvidence = __t.object("PlayerEvidence", {
  evidenceKey: __t.string(),
  playerId: __t.identity(),
  evidenceId: __t.string(),
  discoveredAt: __t.timestamp(),
});
export type PlayerEvidence = __Infer<typeof PlayerEvidence>;

export const PlayerFactionSignal = __t.object("PlayerFactionSignal", {
  signalKey: __t.string(),
  playerId: __t.identity(),
  factionId: __t.string(),
  value: __t.f64(),
  trend: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlayerFactionSignal = __Infer<typeof PlayerFactionSignal>;

export const PlayerFlag = __t.object("PlayerFlag", {
  flagId: __t.string(),
  playerId: __t.identity(),
  key: __t.string(),
  value: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerFlag = __Infer<typeof PlayerFlag>;

export const PlayerInventory = __t.object("PlayerInventory", {
  inventoryKey: __t.string(),
  playerId: __t.identity(),
  itemId: __t.string(),
  quantity: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type PlayerInventory = __Infer<typeof PlayerInventory>;

export const PlayerLocation = __t.object("PlayerLocation", {
  playerId: __t.identity(),
  locationId: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlayerLocation = __Infer<typeof PlayerLocation>;

export const PlayerMapEvent = __t.object("PlayerMapEvent", {
  eventId: __t.string(),
  playerId: __t.identity(),
  templateId: __t.string(),
  snapshotChecksum: __t.string(),
  payloadJson: __t.string(),
  sourceLocationId: __t.string(),
  status: __t.string(),
  spawnedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type PlayerMapEvent = __Infer<typeof PlayerMapEvent>;

export const PlayerMindCase = __t.object("PlayerMindCase", {
  playerCaseKey: __t.string(),
  playerId: __t.identity(),
  caseId: __t.string(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type PlayerMindCase = __Infer<typeof PlayerMindCase>;

export const PlayerMindFact = __t.object("PlayerMindFact", {
  playerFactKey: __t.string(),
  playerId: __t.identity(),
  caseId: __t.string(),
  factId: __t.string(),
  discoveredAt: __t.timestamp(),
});
export type PlayerMindFact = __Infer<typeof PlayerMindFact>;

export const PlayerMindHypothesis = __t.object("PlayerMindHypothesis", {
  playerHypothesisKey: __t.string(),
  playerId: __t.identity(),
  caseId: __t.string(),
  hypothesisId: __t.string(),
  status: __t.string(),
  validatedAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type PlayerMindHypothesis = __Infer<typeof PlayerMindHypothesis>;

export const PlayerNpcFavor = __t.object("PlayerNpcFavor", {
  favorKey: __t.string(),
  playerId: __t.identity(),
  npcId: __t.string(),
  balance: __t.i32(),
  lastReason: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type PlayerNpcFavor = __Infer<typeof PlayerNpcFavor>;

export const PlayerNpcState = __t.object("PlayerNpcState", {
  npcStateKey: __t.string(),
  playerId: __t.identity(),
  npcId: __t.string(),
  trustScore: __t.f64(),
  availabilityState: __t.string(),
  lastMeaningfulContactAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type PlayerNpcState = __Infer<typeof PlayerNpcState>;

export const PlayerProfile = __t.object("PlayerProfile", {
  playerId: __t.identity(),
  nickname: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const PlayerQuest = __t.object("PlayerQuest", {
  questKey: __t.string(),
  playerId: __t.identity(),
  questId: __t.string(),
  stage: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type PlayerQuest = __Infer<typeof PlayerQuest>;

export const PlayerRedeemedCode = __t.object("PlayerRedeemedCode", {
  redemptionId: __t.string(),
  playerId: __t.identity(),
  codeId: __t.string(),
  requestId: __t.string(),
  redeemedAt: __t.timestamp(),
  result: __t.string(),
});
export type PlayerRedeemedCode = __Infer<typeof PlayerRedeemedCode>;

export const PlayerRelationship = __t.object("PlayerRelationship", {
  relationshipKey: __t.string(),
  playerId: __t.identity(),
  characterId: __t.string(),
  value: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type PlayerRelationship = __Infer<typeof PlayerRelationship>;

export const PlayerRumorState = __t.object("PlayerRumorState", {
  rumorStateKey: __t.string(),
  playerId: __t.identity(),
  rumorId: __t.string(),
  status: __t.string(),
  leadPointId: __t.option(__t.string()),
  sourceNpcId: __t.option(__t.string()),
  caseId: __t.string(),
  verificationKind: __t.option(__t.string()),
  verifiedAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type PlayerRumorState = __Infer<typeof PlayerRumorState>;

export const PlayerUnlockGroup = __t.object("PlayerUnlockGroup", {
  unlockKey: __t.string(),
  playerId: __t.identity(),
  groupId: __t.string(),
  unlockedAt: __t.timestamp(),
});
export type PlayerUnlockGroup = __Infer<typeof PlayerUnlockGroup>;

export const PlayerVar = __t.object("PlayerVar", {
  varId: __t.string(),
  playerId: __t.identity(),
  key: __t.string(),
  floatValue: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type PlayerVar = __Infer<typeof PlayerVar>;

export const TelemetryAggregate = __t.object("TelemetryAggregate", {
  aggregateKey: __t.string(),
  bucketStart: __t.timestamp(),
  eventName: __t.string(),
  tagsHash: __t.string(),
  count: __t.u64(),
  sumValue: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TelemetryAggregate = __Infer<typeof TelemetryAggregate>;

export const TelemetryAggregateSchedule = __t.object("TelemetryAggregateSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TelemetryAggregateSchedule = __Infer<typeof TelemetryAggregateSchedule>;

export const TelemetryCleanupSchedule = __t.object("TelemetryCleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TelemetryCleanupSchedule = __Infer<typeof TelemetryCleanupSchedule>;

export const TelemetryEvent = __t.object("TelemetryEvent", {
  eventId: __t.u64(),
  playerId: __t.option(__t.identity()),
  eventName: __t.string(),
  tagsJson: __t.string(),
  value: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
});
export type TelemetryEvent = __Infer<typeof TelemetryEvent>;

export const VnSession = __t.object("VnSession", {
  sessionKey: __t.string(),
  playerId: __t.identity(),
  scenarioId: __t.string(),
  nodeId: __t.string(),
  updatedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type VnSession = __Infer<typeof VnSession>;

export const VnSkillCheckResult = __t.object("VnSkillCheckResult", {
  resultKey: __t.string(),
  playerId: __t.identity(),
  scenarioId: __t.string(),
  nodeId: __t.string(),
  checkId: __t.string(),
  roll: __t.u32(),
  voiceLevel: __t.u32(),
  difficulty: __t.u32(),
  passed: __t.bool(),
  nextNodeId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type VnSkillCheckResult = __Infer<typeof VnSkillCheckResult>;

export const WorkerIdentity = __t.object("WorkerIdentity", {
  identity: __t.identity(),
});
export type WorkerIdentity = __Infer<typeof WorkerIdentity>;

