// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  metricKey: __t.string(),
  label: __t.string(),
  source: __t.string(),
  status: __t.string(),
  summary: __t.string(),
  value: __t.option(__t.f64()),
  unit: __t.option(__t.string()),
  linkUrl: __t.option(__t.string()),
};
