// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  targetType: __t.string(),
  targetId: __t.string(),
  scenarioId: __t.option(__t.string()),
  contentVersion: __t.option(__t.string()),
  visualScore: __t.option(__t.u32()),
  scenicScore: __t.option(__t.u32()),
  textScore: __t.option(__t.u32()),
  overallScore: __t.option(__t.u32()),
  comment: __t.option(__t.string()),
};
