/* auto-generated by scripts/extract-vn-content.ts; do not edit manually */
import type { MapPoint } from "../types";

export const GENERATED_STATIC_FREIBURG_CASE01_POINTS: MapPoint[] = [
  {
    "id": "loc_agency",
    "title": "Grenzwanderer Agency",
    "regionId": "FREIBURG_1905",
    "lat": 47.9952,
    "lng": 7.8508,
    "description": "Your hidden office and operations hub. Briefings, evidence walls, and trusted informants start here.",
    "image": "/images/locations/loc_agency/loc_agency.webp",
    "locationId": "loc_agency",
    "category": "HUB",
    "defaultState": "discovered",
    "bindings": [
      {
        "id": "bind_agency_briefing_start",
        "trigger": "card_primary",
        "label": "Receive First Briefing",
        "priority": 160,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "agency_briefing_complete",
            "value": false
          },
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_agency_briefing"
          }
        ]
      },
      {
        "id": "bind_agency_caseboard",
        "trigger": "card_primary",
        "label": "Review Fritz's Brief",
        "priority": 80,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_hbf_arrival"
          }
        ]
      },
      {
        "id": "bind_agency_student_intro_service",
        "trigger": "card_secondary",
        "label": "Call In Anna's Introduction",
        "priority": 70,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "agency_briefing_complete",
            "value": true
          },
          {
            "type": "rumor_state_is",
            "rumorId": "rumor_bank_rail_yard",
            "status": "verified"
          },
          {
            "type": "flag_is",
            "key": "service_anna_student_intro_unlocked",
            "value": false
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "favor_balance_gte",
                "npcId": "npc_anna_mahler",
                "value": 1
              },
              {
                "type": "agency_standing_gte",
                "value": 15
              }
            ]
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_agency_service_unlock"
          }
        ]
      },
      {
        "id": "bind_agency_promotion_review",
        "trigger": "card_secondary",
        "label": "Review Promotion File",
        "priority": 60,
        "intent": "interaction",
        "conditions": [
          {
            "type": "career_rank_gte",
            "rankId": "junior_detective"
          },
          {
            "type": "flag_is",
            "key": "agency_promotion_review_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_agency_promotion_review"
          }
        ]
      },
      {
        "id": "sys_travel_loc_agency",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_agency"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_hbf",
    "title": "Hauptbahnhof",
    "regionId": "FREIBURG_1905",
    "lat": 47.997791,
    "lng": 7.842609,
    "description": "Steam-era gateway to Freiburg. Arrivals from Basel and Strasbourg.",
    "image": "/images/locations/loc_hbf/loc_hauptbahnhof.webp",
    "locationId": "loc_hbf",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_hbf_demo_reward",
        "trigger": "card_primary",
        "label": "Claim Demo Reward",
        "priority": 150,
        "intent": "interaction",
        "conditions": [
          {
            "type": "var_gte",
            "key": "loop_demo_solved",
            "value": 1
          }
        ],
        "actions": [
          {
            "type": "track_event",
            "eventName": "loop_demo_completed"
          },
          {
            "type": "grant_xp",
            "amount": 100
          }
        ]
      },
      {
        "id": "bind_hbf_intro_start",
        "trigger": "card_primary",
        "label": "Begin Case 01",
        "priority": 130,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_hbf_arrival"
          },
          {
            "type": "track_event",
            "eventName": "case01_hbf_runtime_entry",
            "tags": {
              "location": "hbf"
            }
          }
        ]
      },
      {
        "id": "bind_hbf_case_bridge",
        "trigger": "card_primary",
        "label": "Review Arrival Notes",
        "priority": 95,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "bank_investigation_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "track_event",
            "eventName": "case01_hbf_revisited",
            "tags": {
              "pointId": "loc_hbf"
            }
          }
        ]
      },
      {
        "id": "bind_hbf_verify_rail_yard_rumor",
        "trigger": "card_primary",
        "label": "Verify Rail Yard Whisper",
        "priority": 118,
        "intent": "interaction",
        "conditions": [
          {
            "type": "rumor_state_is",
            "rumorId": "rumor_bank_rail_yard",
            "status": "registered"
          }
        ],
        "actions": [
          {
            "type": "verify_rumor",
            "rumorId": "rumor_bank_rail_yard",
            "verificationKind": "service_unlock"
          },
          {
            "type": "change_agency_standing",
            "delta": 10,
            "reason": "validated_bank_rail_yard_whisper"
          },
          {
            "type": "track_event",
            "eventName": "bank_rail_yard_rumor_verified",
            "tags": {
              "pointId": "loc_hbf"
            }
          }
        ]
      },
      {
        "id": "sys_travel_loc_hbf",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_hbf"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_freiburg_bank",
    "title": "Bankhaus J.A. Krebs",
    "regionId": "FREIBURG_1905",
    "lat": 47.995574,
    "lng": 7.852296,
    "description": "Prestigious bank at Munsterplatz, currently under renovation.",
    "image": "/images/locations/loc_freiburg_bank/loc_bankhaus.webp",
    "locationId": "loc_freiburg_bank",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "unlockGroup": "loc_freiburg_bank",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_bank_start",
        "trigger": "card_primary",
        "label": "Investigate the Bank",
        "priority": 130,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "flag_is",
                "key": "priority_bank_first",
                "value": true
              },
              {
                "type": "flag_is",
                "key": "mayor_briefing_complete",
                "value": true
              },
              {
                "type": "flag_is",
                "key": "origin_detective",
                "value": true
              }
            ]
          },
          {
            "type": "flag_is",
            "key": "bank_investigation_complete",
            "value": false
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "flag_is",
                "key": "origin_detective",
                "value": false
              },
              {
                "type": "flag_is",
                "key": "detective_prologue_done",
                "value": true
              }
            ]
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_bank_investigation"
          }
        ]
      },
      {
        "id": "bind_bank_close",
        "trigger": "card_primary",
        "label": "Close Banker Case",
        "priority": 85,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case_banker_theft_solved",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "bank_investigation_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "set_quest_stage",
            "questId": "quest_banker",
            "stage": 3
          },
          {
            "type": "set_flag",
            "key": "bank_investigation_complete",
            "value": true
          }
        ]
      },
      {
        "id": "sys_travel_loc_freiburg_bank",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_freiburg_bank"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_rathaus",
    "title": "Rathaus",
    "regionId": "FREIBURG_1905",
    "lat": 47.99629692434917,
    "lng": 7.8492596695028,
    "description": "City Hall and records authority for central Freiburg.",
    "image": "/images/locations/loc_rathaus/loc_rathaus_archiv.webp",
    "locationId": "loc_rathaus",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "unlockGroup": "loc_rathaus",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_rathaus_mayor_start",
        "trigger": "card_primary",
        "label": "Meet the Mayor",
        "priority": 125,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "flag_is",
                "key": "priority_mayor_first",
                "value": true
              },
              {
                "type": "flag_is",
                "key": "origin_detective",
                "value": true
              }
            ]
          },
          {
            "type": "flag_is",
            "key": "mayor_briefing_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_mayor_briefing"
          }
        ]
      },
      {
        "id": "bind_rathaus_convergence",
        "trigger": "card_primary",
        "label": "Commit the Route",
        "priority": 110,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "bank_investigation_complete",
            "value": true
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "logic_and",
                "conditions": [
                  {
                    "type": "flag_is",
                    "key": "tailor_lead_complete",
                    "value": true
                  },
                  {
                    "type": "flag_is",
                    "key": "apothecary_lead_complete",
                    "value": true
                  }
                ]
              },
              {
                "type": "logic_and",
                "conditions": [
                  {
                    "type": "flag_is",
                    "key": "tailor_lead_complete",
                    "value": true
                  },
                  {
                    "type": "flag_is",
                    "key": "pub_lead_complete",
                    "value": true
                  }
                ]
              },
              {
                "type": "logic_and",
                "conditions": [
                  {
                    "type": "flag_is",
                    "key": "apothecary_lead_complete",
                    "value": true
                  },
                  {
                    "type": "flag_is",
                    "key": "pub_lead_complete",
                    "value": true
                  }
                ]
              }
            ]
          },
          {
            "type": "var_lte",
            "key": "convergence_route",
            "value": 0
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_convergence"
          }
        ]
      },
      {
        "id": "bind_rathaus_archive_run",
        "trigger": "card_primary",
        "label": "Run the Warrants",
        "priority": 80,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "logic_and",
            "conditions": [
              {
                "type": "var_gte",
                "key": "convergence_route",
                "value": 1
              },
              {
                "type": "var_lte",
                "key": "convergence_route",
                "value": 1
              }
            ]
          },
          {
            "type": "flag_is",
            "key": "warrant_ready",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_archive_warrant_run"
          }
        ]
      },
      {
        "id": "sys_travel_loc_rathaus",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_rathaus"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_munster",
    "title": "Freiburg Munster",
    "regionId": "FREIBURG_1905",
    "lat": 47.9955,
    "lng": 7.8529,
    "description": "Gothic cathedral dominating the city center.",
    "image": "/images/locations/loc_munster/loc_munster.webp",
    "locationId": "loc_munster",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_munster",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_intro_pilot"
          }
        ]
      },
      {
        "id": "sys_travel_loc_munster",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_munster"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_uni_chem",
    "title": "Kiliani Laboratory",
    "regionId": "FREIBURG_1905",
    "lat": 47.994,
    "lng": 7.846,
    "description": "University chemistry lab for forensic analysis.",
    "image": "/images/locations/loc_uni/loc_uni.webp",
    "locationId": "loc_uni_chem",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_uni_chem",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_estate_branch"
          }
        ]
      },
      {
        "id": "sys_travel_loc_uni_chem",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_uni_chem"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_uni_med",
    "title": "Institute of Hygiene",
    "regionId": "FREIBURG_1905",
    "lat": 47.9935,
    "lng": 7.847,
    "description": "Medical institute focused on serology and lab diagnostics.",
    "image": "/images/locations/loc_uni/loc_uni.webp",
    "locationId": "loc_uni_med",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_uni_med",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_estate_branch"
          }
        ]
      },
      {
        "id": "sys_travel_loc_uni_med",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_uni_med"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_student_house",
    "title": "Corps Suevia House",
    "regionId": "FREIBURG_1905",
    "lat": 47.99,
    "lng": 7.848,
    "description": "Fraternity house in the university quarter.",
    "image": "/images/locations/loc_student_house/loc_student_house.webp",
    "locationId": "loc_student_house",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_student_house",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_student_house_access",
        "trigger": "card_primary",
        "label": "Use Anna's Introduction",
        "priority": 110,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "service_anna_student_intro_unlocked",
            "value": true
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "favor_balance_gte",
                "npcId": "npc_anna_mahler",
                "value": 1
              },
              {
                "type": "agency_standing_gte",
                "value": 15
              }
            ]
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_student_house_access"
          }
        ]
      },
      {
        "id": "bind_city_student_tip",
        "trigger": "card_secondary",
        "label": "Talk to Student",
        "priority": 70,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "service_anna_student_intro_unlocked",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "city_student_seen",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_city_student_tip"
          }
        ]
      },
      {
        "id": "sys_travel_loc_student_house",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_student_house"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_pub_deutsche",
    "title": "Zum Deutschen Haus",
    "regionId": "FREIBURG_1905",
    "lat": 47.992,
    "lng": 7.854,
    "description": "Busy inn popular with locals and travelers.",
    "image": "/images/locations/loc_pub_deutsche/loc_ganter_brauerei.webp",
    "locationId": "loc_pub_deutsche",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_pub_deutsche",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_intro_pilot"
          }
        ]
      },
      {
        "id": "sys_travel_loc_pub_deutsche",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_pub_deutsche"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_red_light",
    "title": "Gerberau Canal",
    "regionId": "FREIBURG_1905",
    "lat": 47.993,
    "lng": 7.851,
    "description": "Tanners quarter where movement is best watched at night.",
    "image": "/images/locations/loc_misc/loc_suburbs.webp",
    "locationId": "loc_red_light",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_city_cleaner_tip",
        "trigger": "card_primary",
        "label": "Talk to Cleaner",
        "priority": 80,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "city_cleaner_seen",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_city_cleaner_tip"
          }
        ]
      },
      {
        "id": "sys_travel_loc_red_light",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_red_light"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_freiburg_warehouse",
    "title": "Old Warehouse",
    "regionId": "FREIBURG_1905",
    "lat": 48.001,
    "lng": 7.838,
    "description": "Rail yard storage facility used for late-stage investigation.",
    "image": "/images/locations/loc_freiburg_warehouse/loc_stuhlinger_warehouse.webp",
    "locationId": "loc_freiburg_warehouse",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_freiburg_warehouse",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_warehouse_finale",
        "trigger": "card_primary",
        "label": "Enter Finale",
        "priority": 140,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "warehouse_plan_locked",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "case_resolved",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_warehouse_finale"
          },
          {
            "type": "set_flag",
            "key": "freiburg_finale_open",
            "value": true
          }
        ]
      },
      {
        "id": "bind_warehouse_locked_hint",
        "trigger": "card_primary",
        "label": "Inspect Locked Gate",
        "priority": 20,
        "intent": "interaction",
        "conditions": [
          {
            "type": "logic_not",
            "condition": {
              "type": "flag_is",
              "key": "warehouse_plan_locked",
              "value": true
            }
          }
        ],
        "actions": [
          {
            "type": "track_event",
            "eventName": "warehouse_finale_locked",
            "tags": {
              "pointId": "loc_freiburg_warehouse"
            }
          }
        ]
      },
      {
        "id": "sys_travel_loc_freiburg_warehouse",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_freiburg_warehouse"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_freiburg_estate",
    "title": "Edge Estate",
    "regionId": "FREIBURG_1905",
    "lat": 47.9898,
    "lng": 7.8612,
    "description": "A private estate used as a quiet relay point for the case's hidden paperwork.",
    "image": "/images/locations/loc_student_house/loc_student_house.webp",
    "locationId": "loc_freiburg_estate",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_freiburg_estate",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_estate_trace",
        "trigger": "card_primary",
        "label": "Trace the Estate Ledger",
        "priority": 110,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "bank_investigation_complete",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "estate_branch_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_estate_branch"
          }
        ]
      },
      {
        "id": "sys_travel_loc_freiburg_estate",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_freiburg_estate"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_workers_pub",
    "title": "The Red Cog Tavern",
    "regionId": "FREIBURG_1905",
    "lat": 47.999,
    "lng": 7.839,
    "description": "Workers tavern and hub for social leads.",
    "image": "/images/locations/loc_pub_deutsche/loc_ganter_brauerei.webp",
    "locationId": "loc_workers_pub",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_pub_covert_route",
        "trigger": "card_primary",
        "label": "Work the Backchannel",
        "priority": 150,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "logic_and",
            "conditions": [
              {
                "type": "var_gte",
                "key": "convergence_route",
                "value": 2
              },
              {
                "type": "var_lte",
                "key": "convergence_route",
                "value": 2
              }
            ]
          },
          {
            "type": "flag_is",
            "key": "covert_entry_ready",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_rail_yard_shadow_tail"
          }
        ]
      },
      {
        "id": "bind_pub_rumor_raid",
        "trigger": "card_secondary",
        "label": "Follow Fresh Rumor",
        "priority": 135,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "agency_briefing_complete",
            "value": true
          },
          {
            "type": "logic_not",
            "condition": {
              "type": "rumor_state_is",
              "rumorId": "rumor_bank_rail_yard",
              "status": "verified"
            }
          }
        ],
        "actions": [
          {
            "type": "spawn_map_event",
            "templateId": "evt_workers_pub_raid"
          },
          {
            "type": "track_event",
            "eventName": "workers_pub_rumor_spawned",
            "tags": {
              "templateId": "evt_workers_pub_raid"
            }
          }
        ]
      },
      {
        "id": "bind_pub_dog_close",
        "trigger": "card_primary",
        "label": "Confront Handler",
        "priority": 90,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "dog_reunion_reached",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "dog_route_proven",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "dog_handler_proven",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "dog_case_closed",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "set_quest_stage",
            "questId": "quest_dog",
            "stage": 3
          },
          {
            "type": "set_flag",
            "key": "dog_case_closed",
            "value": true
          },
          {
            "type": "grant_xp",
            "amount": 40
          }
        ]
      },
      {
        "id": "bind_pub_ghost_start",
        "trigger": "card_primary",
        "label": "Start Ghost File",
        "priority": 120,
        "intent": "objective",
        "conditions": [
          {
            "type": "quest_stage_gte",
            "questId": "quest_dog",
            "stage": 2
          },
          {
            "type": "flag_is",
            "key": "ghost_case_closed",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_ghost_pilot"
          },
          {
            "type": "set_quest_stage",
            "questId": "quest_ghost",
            "stage": 1
          }
        ]
      },
      {
        "id": "bind_pub_ghost_followup",
        "trigger": "card_primary",
        "label": "Follow Ghost Leads",
        "priority": 105,
        "intent": "interaction",
        "conditions": [
          {
            "type": "quest_stage_gte",
            "questId": "quest_ghost",
            "stage": 2
          },
          {
            "type": "flag_is",
            "key": "ghost_case_closed",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_ghost_pilot"
          }
        ]
      },
      {
        "id": "bind_pub_ghost_close",
        "trigger": "card_primary",
        "label": "Close Ghost Case",
        "priority": 85,
        "intent": "objective",
        "conditions": [
          {
            "type": "flag_is",
            "key": "ghost_truth_proven",
            "value": true
          },
          {
            "type": "flag_is",
            "key": "ghost_case_closed",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "set_quest_stage",
            "questId": "quest_ghost",
            "stage": 3
          },
          {
            "type": "set_flag",
            "key": "ghost_case_closed",
            "value": true
          },
          {
            "type": "grant_evidence",
            "evidenceId": "ev_ectoplasm"
          }
        ]
      },
      {
        "id": "sys_travel_loc_workers_pub",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_workers_pub"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_martinstor",
    "title": "Martinstor",
    "regionId": "FREIBURG_1905",
    "lat": 47.9936,
    "lng": 7.849,
    "description": "Historic city gate with strong foot traffic.",
    "image": "/images/locations/loc_munster/loc_munster.webp",
    "locationId": "loc_martinstor",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_city_bootblack_tip",
        "trigger": "card_primary",
        "label": "Talk to Bootblack",
        "priority": 80,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "city_bootblack_seen",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_city_bootblack_tip"
          }
        ]
      },
      {
        "id": "sys_travel_loc_martinstor",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_martinstor"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_schwabentor",
    "title": "Schwabentor",
    "regionId": "FREIBURG_1905",
    "lat": 47.9928,
    "lng": 7.8545,
    "description": "Eastern city gate and surveillance vantage point.",
    "image": "/images/locations/loc_munster/loc_munster.webp",
    "locationId": "loc_schwabentor",
    "category": "PUBLIC",
    "defaultState": "discovered",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_schwabentor",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "sandbox_intro_pilot"
          }
        ]
      },
      {
        "id": "sys_travel_loc_schwabentor",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_schwabentor"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_tailor",
    "title": "Tailor Workshop",
    "regionId": "FREIBURG_1905",
    "lat": 47.9935,
    "lng": 7.8525,
    "description": "Disguise and costume workshop tied to lead progression.",
    "image": "/images/locations/loc_student_house/loc_student_house.webp",
    "locationId": "loc_tailor",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_tailor",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_tailor",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_lead_tailor"
          }
        ]
      },
      {
        "id": "sys_travel_loc_tailor",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_tailor"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_apothecary",
    "title": "Lowen Apotheke",
    "regionId": "FREIBURG_1905",
    "lat": 47.9952,
    "lng": 7.8535,
    "description": "Pharmacy near the cathedral with chemical evidence links.",
    "image": "/images/locations/loc_uni/loc_uni.webp",
    "locationId": "loc_apothecary",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_apothecary",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_apothecary",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_lead_apothecary"
          }
        ]
      },
      {
        "id": "sys_travel_loc_apothecary",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_apothecary"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_pub",
    "title": "Zum Schlappen",
    "regionId": "FREIBURG_1905",
    "lat": 47.9938,
    "lng": 7.8495,
    "description": "Tavern near Martinstor with working-class witnesses.",
    "image": "/images/locations/loc_pub_deutsche/loc_ganter_brauerei.webp",
    "locationId": "loc_pub",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_pub",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "legacy_start_loc_pub",
        "trigger": "card_primary",
        "label": "Start Scenario",
        "priority": 100,
        "intent": "interaction",
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_lead_pub"
          }
        ]
      },
      {
        "id": "sys_travel_loc_pub",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_pub"
          }
        ]
      }
    ]
  },
  {
    "id": "loc_telephone",
    "title": "Telegraph Office",
    "regionId": "FREIBURG_1905",
    "lat": 47.9965,
    "lng": 7.8485,
    "description": "Message relay and switchboard narrative checkpoint.",
    "image": "/images/locations/loc_rathaus/loc_rathaus_archiv.webp",
    "locationId": "loc_telephone",
    "category": "SHADOW",
    "defaultState": "locked",
    "unlockGroup": "loc_telephone",
    "isHiddenInitially": true,
    "bindings": [
      {
        "id": "bind_telephone_lotte_interlude",
        "trigger": "card_primary",
        "label": "Answer Lotte's Warning",
        "priority": 105,
        "intent": "interaction",
        "conditions": [
          {
            "type": "flag_is",
            "key": "case01_onboarding_complete",
            "value": true
          },
          {
            "type": "logic_or",
            "conditions": [
              {
                "type": "logic_and",
                "conditions": [
                  {
                    "type": "flag_is",
                    "key": "tailor_lead_complete",
                    "value": true
                  },
                  {
                    "type": "flag_is",
                    "key": "apothecary_lead_complete",
                    "value": true
                  }
                ]
              },
              {
                "type": "logic_and",
                "conditions": [
                  {
                    "type": "flag_is",
                    "key": "tailor_lead_complete",
                    "value": true
                  },
                  {
                    "type": "flag_is",
                    "key": "pub_lead_complete",
                    "value": true
                  }
                ]
              },
              {
                "type": "logic_and",
                "conditions": [
                  {
                    "type": "flag_is",
                    "key": "apothecary_lead_complete",
                    "value": true
                  },
                  {
                    "type": "flag_is",
                    "key": "pub_lead_complete",
                    "value": true
                  }
                ]
              }
            ]
          },
          {
            "type": "flag_is",
            "key": "lotte_interlude_complete",
            "value": false
          }
        ],
        "actions": [
          {
            "type": "start_scenario",
            "scenarioId": "case01_lotte_interlude"
          }
        ]
      },
      {
        "id": "sys_travel_loc_telephone",
        "trigger": "card_secondary",
        "label": "Travel",
        "priority": 10,
        "intent": "travel",
        "actions": [
          {
            "type": "travel_to",
            "locationId": "loc_telephone"
          }
        ]
      }
    ]
  }
] as MapPoint[];
