// AUTO-GENERATED by `bun run content:character:bridge`. Do not hand-edit.
// Source: `knows:` frontmatter in char_*.md (see ADR_008_NPC_Knowledge).
export const KNOWLEDGE_MATRIX: Record<
  string,
  ReadonlyArray<{ fact: string; condition: string }>
> = {
  npc_weber_dispatcher: [
    {
      fact: "ev_eleonora_uncanny_nature",
      condition: "flag:flag_witch_lotte_noticed_strangeness",
    },
    {
      fact: "ev_sasha_narodnaya_volya",
      condition: "never",
    },
  ],
  npc_bureau_master: [
    {
      fact: "ev_sasha_narodnaya_volya",
      condition: "always",
    },
  ],
  npc_sasha_hartmann_servant: [
    {
      fact: "fact_konigsberg_household",
      condition: "always",
    },
    {
      fact: "ev_sasha_russian_exile",
      condition: "always",
    },
    {
      fact: "ev_sasha_narodnaya_volya",
      condition: "always",
    },
    {
      fact: "ev_sasha_war_service",
      condition: "always",
    },
  ],
};
