export enum QuestStateEnum {
  REGISTERED = 'REGISTERED',
  CHARACTER_CREATION = 'CHARACTER_CREATION',
  TRAINING_MISSION = 'TRAINING_MISSION',
  NEW_MESSAGE = 'NEW_MESSAGE',
  DELIVERY_STARTED = 'DELIVERY_STARTED',
  PARTS_COLLECTED = 'PARTS_COLLECTED',
  ARTIFACT_HUNT = 'ARTIFACT_HUNT',
  ARTIFACT_FOUND = 'ARTIFACT_FOUND',
  QUEST_COMPLETION = 'QUEST_COMPLETION',
  FREE_ROAM = 'FREE_ROAM'
}

export enum QuestActionEnum {
  START_GAME = 'START_GAME',
  END_CHARACTER_CREATION = 'END_CHARACTER_CREATION',
  COMPLETE_TRAINING = 'COMPLETE_TRAINING',
  START_DELIVERY_QUEST = 'START_DELIVERY_QUEST',
  TAKE_PARTS = 'TAKE_PARTS',
  ACCEPT_ARTIFACT_QUEST = 'ACCEPT_ARTIFACT_QUEST',
  DECLINE_ARTIFACT_QUEST = 'DECLINE_ARTIFACT_QUEST',
  FIND_ARTIFACT = 'FIND_ARTIFACT',
  HELP_ORK = 'HELP_ORK',
  KILL_BOTH = 'KILL_BOTH',
  IGNORE_ENCOUNTER = 'IGNORE_ENCOUNTER',
  RETURN_TO_CRAFTSMAN = 'RETURN_TO_CRAFTSMAN',
  COMPLETE_DELIVERY_QUEST = 'COMPLETE_DELIVERY_QUEST'
} 