// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceQuestReducer from "../advance_quest_reducer";
import BuyItemReducer from "../buy_item_reducer";
import ChangeRelationshipReducer from "../change_relationship_reducer";
import DeliverThoughtReducer from "../deliver_thought_reducer";
import DiscoverFactReducer from "../discover_fact_reducer";
import EnqueueAiRequestReducer from "../enqueue_ai_request_reducer";
import GrantEvidenceReducer from "../grant_evidence_reducer";
import GrantXpReducer from "../grant_xp_reducer";
import MapInteractReducer from "../map_interact_reducer";
import PerformSkillCheckReducer from "../perform_skill_check_reducer";
import PublishContentReducer from "../publish_content_reducer";
import RecordChoiceReducer from "../record_choice_reducer";
import RegisterWorkerIdentityReducer from "../register_worker_identity_reducer";
import RollbackContentReducer from "../rollback_content_reducer";
import SetFlagReducer from "../set_flag_reducer";
import SetHypothesisFocusReducer from "../set_hypothesis_focus_reducer";
import SetNicknameReducer from "../set_nickname_reducer";
import SetQuestStageReducer from "../set_quest_stage_reducer";
import SetVarReducer from "../set_var_reducer";
import StartMindCaseReducer from "../start_mind_case_reducer";
import StartScenarioReducer from "../start_scenario_reducer";
import TrackEventReducer from "../track_event_reducer";
import TravelToReducer from "../travel_to_reducer";
import UnlockGroupReducer from "../unlock_group_reducer";
import ValidateHypothesisReducer from "../validate_hypothesis_reducer";

export type AdvanceQuestParams = __Infer<typeof AdvanceQuestReducer>;
export type BuyItemParams = __Infer<typeof BuyItemReducer>;
export type ChangeRelationshipParams = __Infer<typeof ChangeRelationshipReducer>;
export type DeliverThoughtParams = __Infer<typeof DeliverThoughtReducer>;
export type DiscoverFactParams = __Infer<typeof DiscoverFactReducer>;
export type EnqueueAiRequestParams = __Infer<typeof EnqueueAiRequestReducer>;
export type GrantEvidenceParams = __Infer<typeof GrantEvidenceReducer>;
export type GrantXpParams = __Infer<typeof GrantXpReducer>;
export type MapInteractParams = __Infer<typeof MapInteractReducer>;
export type PerformSkillCheckParams = __Infer<typeof PerformSkillCheckReducer>;
export type PublishContentParams = __Infer<typeof PublishContentReducer>;
export type RecordChoiceParams = __Infer<typeof RecordChoiceReducer>;
export type RegisterWorkerIdentityParams = __Infer<typeof RegisterWorkerIdentityReducer>;
export type RollbackContentParams = __Infer<typeof RollbackContentReducer>;
export type SetFlagParams = __Infer<typeof SetFlagReducer>;
export type SetHypothesisFocusParams = __Infer<typeof SetHypothesisFocusReducer>;
export type SetNicknameParams = __Infer<typeof SetNicknameReducer>;
export type SetQuestStageParams = __Infer<typeof SetQuestStageReducer>;
export type SetVarParams = __Infer<typeof SetVarReducer>;
export type StartMindCaseParams = __Infer<typeof StartMindCaseReducer>;
export type StartScenarioParams = __Infer<typeof StartScenarioReducer>;
export type TrackEventParams = __Infer<typeof TrackEventReducer>;
export type TravelToParams = __Infer<typeof TravelToReducer>;
export type UnlockGroupParams = __Infer<typeof UnlockGroupReducer>;
export type ValidateHypothesisParams = __Infer<typeof ValidateHypothesisReducer>;

