export const CONTENT_IDS = {
  unlockGroups: new Set<string>([
    "loc_ka_bakery",
    "loc_ka_bank",
    "loc_ka_rathaus",
    "loc_ka_estate",
    "loc_rathaus",
    "loc_freiburg_bank",
    "loc_student_house",
    "loc_freiburg_warehouse",
    "loc_freiburg_estate",
    "loc_tailor",
    "loc_apothecary",
    "loc_pub",
    "loc_telephone",
  ]),
  evidenceIds: new Set<string>([
    "ev_bookshelf_switch",
    "ev_cold_spot",
    "ev_ectoplasm",
    "ev_bank_master_key",
    "ev_karlsruhe_newspaper",
    "ev_aristocrat_seal",
    "ev_veteran_dispatch",
    "ev_archivist_index_card",
  ]),
  characterIds: new Set<string>([
    "npc_banker_kessler",
    "npc_anna_mahler",
    "npc_baroness_elise",
    "npc_major_falk",
    "npc_archivist_otto",
    "npc_weber_dispatcher",
    "assistant",
    "inspector",
    "paperboy",
    "victoria_sterling",
  ]),
  questIds: new Set<string>([
    "quest_banker",
    "quest_dog",
    "quest_ghost",
    "quest_missing_aroma",
    "quest_aristocrat",
    "quest_veteran",
    "quest_archivist",
  ]),
  locationIds: new Set<string>([
    "loc_agency",
    "loc_hbf",
    "loc_freiburg_bank",
    "loc_ka_bank",
    "loc_ka_rathaus",
    "loc_ka_bakery",
    "loc_rathaus",
    "loc_munster",
    "loc_uni_chem",
    "loc_uni_med",
    "loc_student_house",
    "loc_pub_deutsche",
    "loc_red_light",
    "loc_freiburg_warehouse",
    "loc_freiburg_estate",
    "loc_workers_pub",
    "loc_martinstor",
    "loc_schwabentor",
    "loc_tailor",
    "loc_apothecary",
    "loc_pub",
    "loc_street_event",
    "loc_telephone",
  ]),
  mapQrCodeIds: new Set<string>(["qr_warehouse_dock"]),
  mapEventTemplateIds: new Set<string>(["evt_workers_pub_raid"]),
};
