import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const outputPath = path.join(
  repoRoot,
  "spacetimedb",
  "src",
  "generated",
  "bootstrap-config.ts",
);

const hashBootstrapCode = (value: string): string =>
  createHash("sha256").update(value, "utf8").digest("hex");

const resolveBootstrapHash = (): string | null => {
  const explicitHash = process.env.ADMIN_BOOTSTRAP_CODE_HASH?.trim();
  if (explicitHash) {
    return explicitHash;
  }

  const bootstrapCode = process.env.ADMIN_BOOTSTRAP_CODE?.trim();
  if (!bootstrapCode) {
    return null;
  }

  return hashBootstrapCode(bootstrapCode);
};

const bootstrapHash = resolveBootstrapHash();
const fileContent = `// THIS FILE IS GENERATED BY scripts/prepare-bootstrap-config.ts
// DO NOT COMMIT REAL ENVIRONMENT BOOTSTRAP MATERIAL.

export const ADMIN_BOOTSTRAP_CODE_HASH = ${
  bootstrapHash ? JSON.stringify(bootstrapHash) : "null"
};
`;

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, fileContent, "utf8");

console.log(
  bootstrapHash
    ? "[bootstrap-config] wrote admin bootstrap hash."
    : "[bootstrap-config] bootstrap disabled because ADMIN_BOOTSTRAP_CODE/ADMIN_BOOTSTRAP_CODE_HASH is unset.",
);
