import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

type ReleaseProfile = "default" | "karlsruhe_event";

const resolveProfile = (): ReleaseProfile => {
  const rawValue =
    process.env.VITE_RELEASE_PROFILE?.trim() ??
    process.env.RELEASE_PROFILE?.trim() ??
    "default";

  return rawValue === "karlsruhe_event" ? "karlsruhe_event" : "default";
};

const hashToken = (value: string): string =>
  createHash("sha256").update(value, "utf8").digest("hex");

const releaseProfile = resolveProfile();

const spacetimeHost =
  process.env.VITE_SPACETIMEDB_HOST?.trim() ??
  (releaseProfile === "karlsruhe_event"
    ? "https://maincloud.spacetimedb.com"
    : "");

const spacetimeDbName =
  process.env.VITE_SPACETIMEDB_DB_NAME?.trim() ??
  (releaseProfile === "karlsruhe_event" ? "grezwandererdata-karlsruhe" : "");

const entryToken =
  process.env.VITE_KARLSRUHE_ENTRY_TOKEN?.trim() ??
  process.env.KARLSRUHE_ENTRY_TOKEN?.trim() ??
  (releaseProfile === "karlsruhe_event" ? "karlsruhe-start-2026" : "");
const entryTokenHash = entryToken.length > 0 ? hashToken(entryToken) : null;

const frontendOutputPath = path.join(
  repoRoot,
  "src",
  "generated",
  "release-config.ts",
);
const backendOutputPath = path.join(
  repoRoot,
  "spacetimedb",
  "src",
  "generated",
  "release-config.ts",
);

const frontendFileContent = `// THIS FILE IS GENERATED BY scripts/prepare-release-config.ts
// DO NOT COMMIT REAL EVENT TOKENS.

export const GENERATED_RELEASE_PROFILE = ${JSON.stringify(releaseProfile)};
export const GENERATED_KARLSRUHE_ENTRY_TOKEN = ${JSON.stringify(entryToken)};
export const GENERATED_SPACETIMEDB_HOST = ${JSON.stringify(spacetimeHost)};
export const GENERATED_SPACETIMEDB_DB_NAME = ${JSON.stringify(spacetimeDbName)};
`;

const backendFileContent = `// THIS FILE IS GENERATED BY scripts/prepare-release-config.ts
// DO NOT COMMIT REAL EVENT TOKENS.

export const GENERATED_RELEASE_PROFILE = ${JSON.stringify(releaseProfile)};
export const GENERATED_KARLSRUHE_ENTRY_TOKEN_HASH = ${
  entryTokenHash ? JSON.stringify(entryTokenHash) : "null"
};
`;

mkdirSync(path.dirname(frontendOutputPath), { recursive: true });
writeFileSync(frontendOutputPath, frontendFileContent, "utf8");

mkdirSync(path.dirname(backendOutputPath), { recursive: true });
writeFileSync(backendOutputPath, backendFileContent, "utf8");

console.log(
  releaseProfile === "karlsruhe_event"
    ? "[release-config] wrote Karlsruhe release profile configuration."
    : "[release-config] wrote default release profile configuration.",
);
